package principal.vista.productos.marca;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import modelo.producto.marca.Marca;
import repositorio.dao.marca.MarcaDaoImpl;
import principal.vista.gente.HomeMenuGente;
import principal.vista.productos.HomeMenuProductos;

/**
 *
 * @author rodri
 */

public class ListarMarca extends javax.swing.JFrame {

    private JTable marcaTable;
    private JButton listarButton, backButton;
    
    public ListarMarca() {
        setTitle("Listar Marcas");
        setSize(800, 600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);  // Centrar la ventana en la pantalla
        setLayout(new BorderLayout(10, 10));

        // Panel superior para el título
        JPanel titlePanel = new JPanel();
        JLabel titleLabel = new JLabel("Listar Marcas", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 24));
        titlePanel.add(titleLabel);
        add(titlePanel, BorderLayout.NORTH);

        // Panel de filtro para el código de la marca (opcional)
        JPanel filterPanel = new JPanel(new GridLayout(1, 2, 10, 10));
        filterPanel.add(new JLabel("Código de la Marca (Opcional):"));
        JTextField codigoField = new JTextField();
        filterPanel.add(codigoField);

        listarButton = new JButton("Listar");
        listarButton.addActionListener(new ListarButtonListener(codigoField));  // Pasamos el campo de código al listener
        filterPanel.add(listarButton);

        add(filterPanel, BorderLayout.NORTH);

        // Tabla para listar las marcas
        String[] columnNames = {"Código", "Nombre"};
        marcaTable = new JTable(new Object[0][2], columnNames);
        JScrollPane scrollPane = new JScrollPane(marcaTable);
        add(scrollPane, BorderLayout.CENTER);

        // Panel inferior para el botón de volver
        JPanel buttonPanel = new JPanel(new FlowLayout());

        backButton = new JButton("Volver");
        backButton.addActionListener(e -> {
            new HomeMenuProductos().setVisible(true);
            dispose();
        });
        buttonPanel.add(backButton);

        add(buttonPanel, BorderLayout.SOUTH);
    }

    private class ListarButtonListener implements ActionListener {

        private JTextField codigoField;

        public ListarButtonListener(JTextField codigoField) {
            this.codigoField = codigoField;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            String codigoText = codigoField.getText().trim();
            int codigo = codigoText.isEmpty() ? 0 : Integer.parseInt(codigoText);  // Si el campo está vacío, buscará todas las marcas
            actualizarTablaMarcas(codigo);
        }
    }

    private void actualizarTablaMarcas(int codigo) {
        MarcaDaoImpl marcaDao = new MarcaDaoImpl();
        List<Marca> marcas = marcaDao.getMarcas(codigo, null);  // Llamar al método para listar marcas con el código (si se proporciona)

        Object[][] data = new Object[marcas.size()][2];
        for (int i = 0; i < marcas.size(); i++) {
            Marca marca = marcas.get(i);
            data[i][0] = marca.getId();
            data[i][1] = marca.getMarca();
        }

        marcaTable.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{"Código", "Nombre"}
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarMarca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
